services:
    web:
        container_name: find-a-friend-web
        build:
            dockerfile: Dockerfile
            target: base
        entrypoint: sh -c "npm ci && npm run dev:docker"
        ports:
            - 5173:5173
        volumes:
            - ./:/home/node/app
        networks:
            - find-a-friend-network

networks:
    find-a-friend-network:
        name: find-a-friend-network
        driver: bridge
        external: true
